version: '3.9'

services:
  # --------------------------------------
  # Postgres
  # --------------------------------------
  pgsql:
    image: postgres:13.0-alpine
    container_name: pgsql
    env_file:
      - ./stripe/.env
    ports:
      - "5432:5432"
  # --------------------------------------
  # Application
  # --------------------------------------
  stripe:
    build: .
    container_name: stripe
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stripe:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./stripe/.env
    depends_on:
      - pgsql
  # --------------------------------------
  # Nginx
  # --------------------------------------
  nginx:
    build: ./nginx/
    container_name: nginx
    restart: on-failure
    ports:
      - "81:81"
    depends_on:
      - stripe